name: Ansible Lint
description: Run Ansible Lint
author: Ansible by Red Hat <info@ansible.com>
branding:
  icon: shield
  color: red
inputs:
  python_version:
    required: false
    default: "3.11"
  ansible_version:
    required: false
    default: "7.2.0"
  path:
    description: >
      Specific path to lint instead of the default `.`. Multiple arguments are
      not supported and you will need to alter linter configuration to
      accommodate other use cases.
    required: false
    # That default is just a placeholder workaround for no arguments use-case
    # Feeding "." or empty string to ansible-lint makes it believe it is a role
    default: --show-relpath
  args:
    description: deprecated
    deprecationMessage: >
      Arbitrary args are no longer accepted, please use path instead and
      linter own configuration file to change its behavior.
    required: false
    default: ""
runs:
  using: docker
  image: docker://registry.gitlab.com/famedly/infra/containers/ansible-test-suite:py${{ inputs.python_version }}-ansible${{ inputs.ansible_version }}
  entrypoint: /usr/local/bin/ansible-lint
  env:
    # These tell ansible-lint to use github compatible annotation format:
    GITHUB_ACTIONS: "true"
    GITHUB_WORKFLOW: "{{ github.workflow.name }}"
    ANSIBLE_COLLECTIONS_PATHS: "/github/workspace"
  args:
    - --offline
    - --profile
    - safety
    - --skip-list
    - name[play],name[template],fqcn[action-core],no-tabs
    - --enable-list
    - no-handler,no-relative-paths,ignore-errors,meta-incorrect,meta-no-info,meta-no-tags,fqcn
    - ${{ inputs.path }}
